version: 2
updates:
  - die: &I didn't edit my config file
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:05"
      timezone: "Europe/Lisbon"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:05"
      timezone: "Europe/Lisbon"
