name: CI

on:
  push:
    branches:
      - main
      - release-please--branches--main--components--dependabot-test
  pull_request:
    branches:
      - main
      - release-please--branches--main--components--dependabot-test
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install
