name: Hello World Workflow
on: push

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World!"
